# saas_analyzer/analyzer/java/parse_java/engine.py

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, Optional, Sequence

from .models import JavaParsedFile
from . import regex_engine
from . import javaparser_engine


def _engine_choice() -> str:
    v = os.environ.get("PVIZ_JAVA_PARSER_ENGINE", "auto").strip().lower()
    if v not in {"auto", "regex", "javaparser"}:
        return "auto"
    return v


def parse_java_file(path: Path) -> JavaParsedFile:
    """
    Public single-file parse entry: chooses engine.

    Kept for backwards compatibility and small-file/manual paths.
    """
    choice = _engine_choice()

    if choice == "regex":
        return regex_engine.parse_java_file(path)

    if choice == "javaparser":
        return javaparser_engine.parse_java_file(path)

    # auto: try javaparser first; fall back to regex if jar/java unavailable or parse error
    jf = javaparser_engine.parse_java_file(path)
    if jf.parse_status == "ok":
        return jf

    return regex_engine.parse_java_file(path)


def parse_java_files(
    paths: Sequence[Path],
    *,
    repo_root: Optional[Path] = None,
) -> Dict[str, JavaParsedFile]:
    """
    Public batch parse entry.

    Returns:
      dict[str, JavaParsedFile]

    Keys are POSIX-ish path strings generated by the selected engine.
    In normal FolderIndex usage, callers should still normalize keys with
    repo_rel(path, root) before final storage.

    Engine behavior:
      - regex: in-process per-file parse
      - javaparser: preferred batch jar invocation, with internal fallback to per-file
      - auto: preferred JavaParser batch; regex fallback for files that fail
    """
    files = [Path(p) for p in paths]
    choice = _engine_choice()

    if not files:
        return {}

    if choice == "regex":
        return {
            str(p): regex_engine.parse_java_file(p)
            for p in files
        }

    if choice == "javaparser":
        return javaparser_engine.parse_java_files(files, repo_root=repo_root)

    # auto mode:
    # Use JavaParser batch first. If a file returns an error, replace that file
    # with regex output so the pipeline does not collapse because of one JavaParser issue.
    parsed = javaparser_engine.parse_java_files(files, repo_root=repo_root)

    out: Dict[str, JavaParsedFile] = {}
    parsed_by_resolved = {
        str(Path(pf.path).resolve()): pf
        for pf in parsed.values()
        if isinstance(pf, JavaParsedFile)
    }

    for path in files:
        key = str(path)
        resolved_key = str(path.resolve())

        jf = parsed_by_resolved.get(resolved_key)
        if jf is None:
            # Missing result from batch mode. Fall back to regex in auto mode.
            out[key] = regex_engine.parse_java_file(path)
            continue

        if jf.parse_status == "ok":
            out[key] = jf
        else:
            out[key] = regex_engine.parse_java_file(path)

    return out


# Text-based extractors:
# Keep these regex-backed. They are cheap and do not need the JavaParser CLI.
extract_package = regex_engine.extract_package
extract_declared_types = regex_engine.extract_declared_types
extract_imports = regex_engine.extract_imports